### ISSUE TITLE
Build failure needs to be fixed

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/Multitool#34]
Currently the azure build "IntelliTect.IntelliTect" is reporting as failing.

**Comment by philspokas** [comment]
@BenjaminMichaelis or @Keboo or @MarkMichaelis Can I be made an admin in this repo so I can take a look at this as well as review how the this is setup?

**Comment by Keboo** [comment]
@adamskt it looks like Phil needs to be in "IntelliTect Core Contributors" can you add him plz

**Comment by BenjaminMichaelis** [comment]
@Keboo @philspokas Done!

**Comment by philspokas** [comment]
thanks!

**Comment by BenjaminMichaelis** [comment]
Completed with #38
